import { Question } from '../types';

export const mathQuestions: Question[] = [
    // === ALJABAR LINEAR ===
    {
        id: 'math-01',
        type: 'multiple-choice',
        question: 'Tentukan nilai x dari persamaan 2x + 6 = 14',
        options: ['2', '4', '6', '8'],
        answer: '4',
        explanation: '2x + 6 = 14 → 2x = 8 → x = 4',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-02',
        type: 'type-answer',
        question: 'Jika 3x − 5 = 16, berapakah nilai x?',
        answer: '7',
        explanation: '3x − 5 = 16 → 3x = 21 → x = 7',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-03',
        type: 'true-false',
        question: 'Persamaan 5x − 3 = 2x + 9 memiliki solusi x = 4',
        answer: 'true',
        explanation: '5(4) − 3 = 17 dan 2(4) + 9 = 17. Kedua ruas sama, jadi benar.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-04',
        type: 'drag-drop',
        question: 'Pasangkan persamaan dengan solusinya:',
        pairs: [
            { left: 'x + 5 = 12', right: 'x = 7' },
            { left: '2x = 18', right: 'x = 9' },
            { left: 'x − 3 = 10', right: 'x = 13' },
        ],
        answer: ['x + 5 = 12::x = 7', '2x = 18::x = 9', 'x − 3 = 10::x = 13'],
        explanation: 'Selesaikan masing-masing persamaan linear satu variabel.',
        points: 15,
        difficulty: 'medium',
    },

    // === FUNGSI KUADRAT ===
    {
        id: 'math-05',
        type: 'multiple-choice',
        question: 'Akar-akar dari x² − 5x + 6 = 0 adalah ...',
        options: ['x = 2 dan x = 3', 'x = 1 dan x = 6', 'x = −2 dan x = −3', 'x = −1 dan x = −6'],
        answer: 'x = 2 dan x = 3',
        explanation: 'x² − 5x + 6 = (x − 2)(x − 3) = 0, maka x = 2 atau x = 3.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-06',
        type: 'type-answer',
        question: 'Tentukan diskriminan dari persamaan x² + 4x + 4 = 0',
        answer: '0',
        explanation: 'D = b² − 4ac = 16 − 16 = 0. Persamaan memiliki akar kembar.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-07',
        type: 'true-false',
        question: 'Grafik fungsi f(x) = x² − 4 memotong sumbu-x di titik (2, 0) dan (−2, 0)',
        answer: 'true',
        explanation: 'x² − 4 = 0 → x² = 4 → x = ±2. Jadi memotong sumbu-x di (2,0) dan (−2,0).',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-08',
        type: 'multiple-choice',
        question: 'Titik puncak parabola y = x² − 6x + 5 adalah ...',
        options: ['(3, −4)', '(3, 4)', '(−3, −4)', '(6, 5)'],
        answer: '(3, −4)',
        explanation: 'xp = −b/2a = 6/2 = 3, yp = 9 − 18 + 5 = −4. Titik puncak = (3, −4).',
        points: 15,
        difficulty: 'medium',
    },

    // === TRIGONOMETRI ===
    {
        id: 'math-09',
        type: 'multiple-choice',
        question: 'Nilai dari sin 30° adalah ...',
        options: ['1/2', '√2/2', '√3/2', '1'],
        answer: '1/2',
        explanation: 'sin 30° = 1/2 merupakan nilai trigonometri sudut istimewa.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-10',
        type: 'type-answer',
        question: 'Berapa nilai cos 60° ? (jawab dalam pecahan sederhana, contoh: 1/2)',
        answer: '1/2',
        explanation: 'cos 60° = 1/2 merupakan sudut istimewa trigonometri.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-11',
        type: 'true-false',
        question: 'tan 45° = 1',
        answer: 'true',
        explanation: 'tan 45° = sin 45° / cos 45° = (√2/2) / (√2/2) = 1.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-12',
        type: 'drag-drop',
        question: 'Pasangkan fungsi trigonometri dengan nilainya:',
        pairs: [
            { left: 'sin 90°', right: '1' },
            { left: 'cos 0°', right: '1' },
            { left: 'tan 0°', right: '0' },
        ],
        answer: ['sin 90°::1', 'cos 0°::1', 'tan 0°::0'],
        explanation: 'sin 90° = 1, cos 0° = 1, tan 0° = 0.',
        points: 15,
        difficulty: 'medium',
    },

    // === PELUANG ===
    {
        id: 'math-13',
        type: 'multiple-choice',
        question: 'Sebuah dadu dilempar sekali. Peluang muncul angka genap adalah ...',
        options: ['1/2', '1/3', '1/6', '2/3'],
        answer: '1/2',
        explanation: 'Angka genap = {2, 4, 6}, ada 3 dari 6 kemungkinan. P = 3/6 = 1/2.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-14',
        type: 'type-answer',
        question: 'Sebuah koin dilempar 2 kali. Berapa banyak ruang sampel? (jawab angka)',
        answer: '4',
        explanation: 'Ruang sampel = {AA, AG, GA, GG} = 4 kejadian.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-15',
        type: 'true-false',
        question: 'Peluang suatu kejadian selalu bernilai antara 0 dan 1 (inklusif)',
        answer: 'true',
        explanation: '0 ≤ P(A) ≤ 1 untuk setiap kejadian A.',
        points: 10,
        difficulty: 'easy',
    },

    // === STATISTIKA ===
    {
        id: 'math-16',
        type: 'multiple-choice',
        question: 'Rata-rata dari data 4, 6, 8, 10, 12 adalah ...',
        options: ['8', '7', '9', '10'],
        answer: '8',
        explanation: 'Rata-rata = (4+6+8+10+12)/5 = 40/5 = 8.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-17',
        type: 'type-answer',
        question: 'Tentukan median dari data: 3, 7, 2, 9, 5',
        answer: '5',
        explanation: 'Urutkan: 2, 3, 5, 7, 9. Median (nilai tengah) = 5.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-18',
        type: 'true-false',
        question: 'Modus dari data 2, 3, 3, 5, 7, 7, 7 adalah 3',
        answer: 'false',
        explanation: 'Modus adalah data yang paling sering muncul, yaitu 7 (muncul 3 kali).',
        points: 10,
        difficulty: 'easy',
    },

    // === LIMIT DASAR ===
    {
        id: 'math-19',
        type: 'multiple-choice',
        question: 'Nilai dari lim(x→2) (x² − 4)/(x − 2) adalah ...',
        options: ['4', '2', '0', 'Tidak ada'],
        answer: '4',
        explanation: 'Faktorkan: (x²−4)/(x−2) = (x+2)(x−2)/(x−2) = x+2. Substitusi x=2: 2+2 = 4.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-20',
        type: 'type-answer',
        question: 'Tentukan nilai lim(x→3) (2x + 1)',
        answer: '7',
        explanation: 'Substitusi langsung: 2(3) + 1 = 7.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-21',
        type: 'multiple-choice',
        question: 'Nilai lim(x→0) (sin x)/x adalah ...',
        options: ['1', '0', '∞', 'Tidak ada'],
        answer: '1',
        explanation: 'Ini adalah limit trigonometri dasar: lim(x→0) sin(x)/x = 1.',
        points: 20,
        difficulty: 'hard',
    },
    {
        id: 'math-22',
        type: 'drag-drop',
        question: 'Pasangkan limit dengan hasilnya:',
        pairs: [
            { left: 'lim(x→1) x²', right: '1' },
            { left: 'lim(x→0) (x+5)', right: '5' },
            { left: 'lim(x→4) √x', right: '2' },
        ],
        answer: ['lim(x→1) x²::1', 'lim(x→0) (x+5)::5', 'lim(x→4) √x::2'],
        explanation: 'Substitusi langsung pada masing-masing fungsi.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-23',
        type: 'true-false',
        question: 'lim(x→∞) 1/x = 0',
        answer: 'true',
        explanation: 'Ketika x mendekati tak hingga, 1/x mendekati 0.',
        points: 15,
        difficulty: 'medium',
    },
];
