import { Question } from '../types';

export const pknQuestions: Question[] = [
    // === PANCASILA & IMPLEMENTASINYA ===
    {
        id: 'pkn-01',
        type: 'multiple-choice',
        question: 'Bunyi sila kedua Pancasila adalah ...',
        options: [
            'Kemanusiaan yang adil dan beradab',
            'Persatuan Indonesia',
            'Ketuhanan Yang Maha Esa',
            'Keadilan sosial bagi seluruh rakyat Indonesia',
        ],
        answer: 'Kemanusiaan yang adil dan beradab',
        explanation: 'Sila kedua Pancasila berbunyi "Kemanusiaan yang adil dan beradab" yang menekankan pengakuan HAM.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-02',
        type: 'drag-drop',
        question: 'Pasangkan sila Pancasila dengan lambangnya:',
        pairs: [
            { left: 'Sila ke-1', right: 'Bintang' },
            { left: 'Sila ke-2', right: 'Rantai' },
            { left: 'Sila ke-3', right: 'Pohon Beringin' },
        ],
        answer: ['Sila ke-1::Bintang', 'Sila ke-2::Rantai', 'Sila ke-3::Pohon Beringin'],
        explanation: 'Bintang = Ketuhanan YME, Rantai = Kemanusiaan, Pohon Beringin = Persatuan Indonesia.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-03',
        type: 'true-false',
        question: 'Pancasila ditetapkan sebagai dasar negara pada tanggal 18 Agustus 1945',
        answer: 'true',
        explanation: 'Pancasila disahkan dalam sidang PPKI tanggal 18 Agustus 1945 bersamaan dengan UUD 1945.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-04',
        type: 'type-answer',
        question: 'Siapakah yang pertama kali mengusulkan nama "Pancasila" sebagai dasar negara? (jawab nama belakang)',
        answer: 'Soekarno',
        explanation: 'Ir. Soekarno mengusulkan nama Pancasila pada sidang BPUPKI tanggal 1 Juni 1945.',
        points: 10,
        difficulty: 'easy',
    },

    // === UUD 1945 PASAL PENTING ===
    {
        id: 'pkn-05',
        type: 'multiple-choice',
        question: 'Pasal berapa dalam UUD 1945 yang mengatur tentang hak beragama?',
        options: ['Pasal 29', 'Pasal 27', 'Pasal 31', 'Pasal 33'],
        answer: 'Pasal 29',
        explanation: 'Pasal 29 UUD 1945 mengatur tentang kebebasan beragama dan beribadah.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-06',
        type: 'true-false',
        question: 'Pasal 31 UUD 1945 mengatur tentang hak setiap warga negara untuk mendapat pendidikan',
        answer: 'true',
        explanation: 'Pasal 31 ayat (1): "Setiap warga negara berhak mendapat pendidikan."',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-07',
        type: 'drag-drop',
        question: 'Pasangkan pasal UUD 1945 dengan isinya:',
        pairs: [
            { left: 'Pasal 27', right: 'Persamaan kedudukan di hukum' },
            { left: 'Pasal 28', right: 'Kemerdekaan berserikat' },
            { left: 'Pasal 33', right: 'Perekonomian nasional' },
        ],
        answer: ['Pasal 27::Persamaan kedudukan di hukum', 'Pasal 28::Kemerdekaan berserikat', 'Pasal 33::Perekonomian nasional'],
        explanation: 'Pasal 27 tentang hukum, Pasal 28 tentang berserikat, Pasal 33 tentang ekonomi.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-08',
        type: 'type-answer',
        question: 'UUD 1945 telah mengalami berapa kali amandemen? (jawab angka)',
        answer: '4',
        explanation: 'UUD 1945 diamandemen sebanyak 4 kali: tahun 1999, 2000, 2001, dan 2002.',
        points: 10,
        difficulty: 'easy',
    },

    // === SISTEM PEMERINTAHAN RI ===
    {
        id: 'pkn-09',
        type: 'multiple-choice',
        question: 'Sistem pemerintahan yang dianut Indonesia adalah ...',
        options: ['Presidensial', 'Parlementer', 'Semi-presidensial', 'Monarki konstitusional'],
        answer: 'Presidensial',
        explanation: 'Indonesia menganut sistem presidensial di mana presiden sebagai kepala negara sekaligus kepala pemerintahan.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-10',
        type: 'true-false',
        question: 'Dalam sistem presidensial Indonesia, presiden dipilih langsung oleh rakyat',
        answer: 'true',
        explanation: 'Sejak amandemen UUD 1945, presiden dan wakil presiden dipilih secara langsung oleh rakyat melalui pemilu.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-11',
        type: 'multiple-choice',
        question: 'Masa jabatan presiden Indonesia adalah ...',
        options: ['5 tahun', '4 tahun', '6 tahun', '7 tahun'],
        answer: '5 tahun',
        explanation: 'Berdasarkan Pasal 7 UUD 1945, presiden memegang jabatan selama 5 tahun dan dapat dipilih kembali untuk satu kali masa jabatan.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-12',
        type: 'type-answer',
        question: 'Apa bentuk negara Indonesia? (jawab satu kata)',
        answer: 'Republik',
        explanation: 'Pasal 1 ayat (1) UUD 1945: "Negara Indonesia ialah Negara Kesatuan yang berbentuk Republik."',
        points: 10,
        difficulty: 'easy',
    },

    // === HAK & KEWAJIBAN WARGA NEGARA ===
    {
        id: 'pkn-13',
        type: 'multiple-choice',
        question: 'Berikut yang merupakan kewajiban warga negara Indonesia menurut UUD 1945, kecuali ...',
        options: [
            'Mendapatkan pekerjaan yang layak',
            'Membela negara',
            'Menaati hukum dan pemerintahan',
            'Membayar pajak',
        ],
        answer: 'Mendapatkan pekerjaan yang layak',
        explanation: 'Mendapatkan pekerjaan yang layak adalah HAK warga negara (Pasal 27 ayat 2), bukan kewajiban.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-14',
        type: 'drag-drop',
        question: 'Klasifikasikan mana yang termasuk hak dan mana kewajiban warga negara:',
        pairs: [
            { left: 'Mendapat pendidikan', right: 'Hak' },
            { left: 'Membela negara', right: 'Kewajiban' },
            { left: 'Membayar pajak', right: 'Kewajiban' },
        ],
        answer: ['Mendapat pendidikan::Hak', 'Membela negara::Kewajiban', 'Membayar pajak::Kewajiban'],
        explanation: 'Pendidikan adalah hak (Pasal 31). Membela negara (Pasal 27 ayat 3) dan membayar pajak (Pasal 23A) adalah kewajiban.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-15',
        type: 'true-false',
        question: 'Setiap warga negara berhak atas pekerjaan dan penghidupan yang layak menurut UUD 1945',
        answer: 'true',
        explanation: 'Pasal 27 ayat (2) UUD 1945 menjamin hak atas pekerjaan dan penghidupan yang layak.',
        points: 10,
        difficulty: 'easy',
    },

    // === DEMOKRASI & PEMILU ===
    {
        id: 'pkn-16',
        type: 'multiple-choice',
        question: 'Asas pemilu di Indonesia dikenal dengan singkatan ...',
        options: ['LUBER JURDIL', 'LUBER JUDIL', 'LUBERJUR DINAS', 'JUJUR ADIL'],
        answer: 'LUBER JURDIL',
        explanation: 'LUBER JURDIL = Langsung, Umum, Bebas, Rahasia, Jujur, dan Adil.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-17',
        type: 'type-answer',
        question: 'Lembaga yang menyelenggarakan pemilu di Indonesia adalah ... (singkatan 3 huruf)',
        answer: 'KPU',
        explanation: 'KPU (Komisi Pemilihan Umum) adalah lembaga yang menyelenggarakan pemilu.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-18',
        type: 'true-false',
        question: 'Indonesia menganut demokrasi Pancasila, bukan demokrasi liberal',
        answer: 'true',
        explanation: 'Indonesia menganut demokrasi Pancasila yang berlandaskan nilai-nilai Pancasila, bukan demokrasi liberal ala Barat.',
        points: 10,
        difficulty: 'easy',
    },

    // === LEMBAGA NEGARA ===
    {
        id: 'pkn-19',
        type: 'multiple-choice',
        question: 'Lembaga negara yang berwenang mengadili pada tingkat kasasi adalah ...',
        options: ['Mahkamah Agung', 'Mahkamah Konstitusi', 'Komisi Yudisial', 'DPR'],
        answer: 'Mahkamah Agung',
        explanation: 'MA berwenang mengadili pada tingkat kasasi dan menguji peraturan perundang-undangan di bawah UU.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-20',
        type: 'drag-drop',
        question: 'Pasangkan lembaga negara dengan fungsinya:',
        pairs: [
            { left: 'DPR', right: 'Legislatif' },
            { left: 'Presiden', right: 'Eksekutif' },
            { left: 'MA', right: 'Yudikatif' },
        ],
        answer: ['DPR::Legislatif', 'Presiden::Eksekutif', 'MA::Yudikatif'],
        explanation: 'DPR = pembuat UU (legislatif), Presiden = pelaksana pemerintahan (eksekutif), MA = pelaksana kekuasaan kehakiman (yudikatif).',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-21',
        type: 'type-answer',
        question: 'Lembaga yang berwenang menguji UU terhadap UUD adalah ... (dua kata, singkatan)',
        answer: 'MK',
        explanation: 'Mahkamah Konstitusi (MK) berwenang menguji undang-undang terhadap UUD 1945.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-22',
        type: 'multiple-choice',
        question: 'MPR terdiri dari anggota ...',
        options: [
            'DPR dan DPD',
            'DPR dan BPK',
            'DPD dan MA',
            'DPR dan Presiden',
        ],
        answer: 'DPR dan DPD',
        explanation: 'Pasal 2 ayat (1) UUD 1945: MPR terdiri atas anggota DPR dan anggota DPD.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-23',
        type: 'true-false',
        question: 'BPK (Badan Pemeriksa Keuangan) bertugas memeriksa pengelolaan keuangan negara',
        answer: 'true',
        explanation: 'Pasal 23E UUD 1945: BPK bertugas memeriksa pengelolaan dan tanggung jawab tentang keuangan negara.',
        points: 10,
        difficulty: 'easy',
    },
];
